# These are supported funding model platforms

github: leonstafford
custom: ['https://paypal.me/ljsdotdev', 'https://ljs.dev', 'https://donorbox.org/leonstafford']
patreon: leonstafford
ko_fi: leonstafford

