name: codequality

on:
  push:
    branches:
    - master
    - develop
  pull_request:
    branches:
    - master
    - develop
jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ["7.4", "8.0]

    name: PHP-${{ matrix.php }} 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
        coverage: none

    - name: Validate Composer
      run: composer validate --strict

    - name: Install PHP dependencies
      run: composer install --no-interaction

    - name: Run our Linter and PHPStan
      run: composer run-script test
